LOCAL_PATH :=

PLATFORM_PATH := device/BLU/BLU_STUDIO_G2

TARGET_SPECIFIC_HEADER_PATH := device/BLU/BLU_STUDIO_G2/include

DEVICE_PATH := device/BLU/BLU_STUDIO_G2

BOARD_VENDOR := BLU

USE_CAMERA_STUB := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := BLU_STUDIO_G2
TARGET_NO_BOOTLOADER := true

# Platform
TARGET_BOARD_PLATFORM := mt6580
TARGET_BOARD_PLATFORM_GPU := mali-400

# inherit from the proprietary version
-include vendor/BLU/BLU_STUDIO_G2/BoardConfigVendor.mk

# Architecture
TARGET_ARCH := arm
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

# Kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32S1,32S1
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_TAGS_OFFSET := 00008000
BOARD_RAMDISK_OFFSET := 04000000
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_HEADER_ARCH := arm
TARGET_KERNEL_SOURCE := kernel/BLU/mt6580
TARGET_KERNEL_CONFIG := BLU_STUDIO_G2_defconfig
TARGET_KERNEL_CROSS_COMPILE_PREFIX := arm-eabi-

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x1000000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x1000000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x7a000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x60000000
BOARD_FLASH_BLOCK_SIZE := 0x20000

#TARGET_PREBUILT_KERNEL := device/BLU/BLU_STUDIO_G2/prebuilt/kernel

BOARD_HAS_NO_SELECT_BUTTON := true

TARGET_SYSTEM_PROP := $(LOCAL_PATH)/system.prop
