PLATFORM_PATH := device/ratech/d5170_blu_gmo

TARGET_SPECIFIC_HEADER_PATH := device/ratech/d5170_blu_gmo/kernel-headers

DEVICE_PATH := device/ratech/d5170_blu_gmo

BOARD_VENDOR := mediatek

USE_CAMERA_STUB := true

# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/ratech/d5170_blu_gmo/bluetooth

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := d5170_blu_gmo
TARGET_NO_BOOTLOADER := true

# Display
TARGET_USES_OVERLAY := true
USE_OPENGL_RENDERER := true

# Platform
TARGET_BOARD_PLATFORM := mt6580
TARGET_BOARD_PLATFORM_GPU := mali-400

# inherit from the proprietary version
-include vendor/ratech/d5170_blu_gmo/BoardConfigVendor.mk

# Architecture
TARGET_ARCH := arm
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

# Kernel
BOARD_KERNEL_CMDLINE := bootopt=64S3,32S1,32S1
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_TAGS_OFFSET := 00008000
BOARD_RAMDISK_OFFSET := 04000000
BOARD_KERNEL_IMAGE_NAME := zImage
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_HEADER_ARCH := arm
TARGET_KERNEL_SOURCE := kernel/ratech/d5170_blu_gmo
TARGET_KERNEL_CONFIG := d5170_blu_gmo_defconfig
TARGET_KERNEL_CROSS_COMPILE_PREFIX := arm-eabi-

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x1000000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x1000000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x7a000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x60000000
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 4096

#TWRP
RECOVERY_VARIANT := twrp
TW_THEME := portrait_mdpi
RECOVERY_SDCARD_ON_DATA :=
BOARD_HAS_NO_REAL_SDCARD := true
TW_NO_BATT_PERCENT := false
TW_CUSTOM_POWER_BUTTON :=
TW_NO_REBOOT_BOOTLOADER := false
TW_NO_REBOOT_RECOVERY := false
RECOVERY_TOUCHSCREEN_SWAP_XY := false
RECOVERY_TOUCHSCREEN_FLIP_Y := false
RECOVERY_TOUCHSCREEN_FLIP_X := false
TWRP_EVENT_LOGGING := true
BOARD_HAS_FLIPPED_SCREEN := false

# Hardware
BOARD_HARDWARE_CLASS := device/ratech/d5170_blu_gmo/cmhw

# Prebuilts
#TARGET_PREBUILT_KERNEL := device/ratech/d5170_blu_gmo/prebuilt/kernel

BOARD_HAS_NO_SELECT_BUTTON := true

TARGET_SYSTEM_PROP := $(PLATFORM_PATH)/system.prop
